[build]
builder = "nixpacks"

[deploy]
startCommand = "npm api.js & python3 web_app.py"

[env]
PORT = "8080"
NODE_ENV = "production"
PYTHONIOENCODING = "utf-8"
LANG = "C.UTF-8"
LC_ALL = "C.UTF-8"
PYTHONUTF8 = "1"
TELEGRAM_BOT_TOKEN = "8328551756:AAEWPTFIWrREap94-pL86p6-nWM_3UJcB2g"
